// src-tauri/resources/templates/vue-ts-vite/src/App.vue
<template>
  <div class="app">
    <h1>Hello World</h1>
    <p>Welcome to your Vue + TypeScript + Vite app.</p>
  </div>
</template>

<script setup lang="ts">
</script>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background-color: #242424;
  color: #ffffffde;
  min-height: 100vh;
}

.app {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  text-align: center;
}

.app h1 {
  font-size: 3rem;
  margin-bottom: 1rem;
}

.app p {
  font-size: 1.2rem;
  color: #888;
}
</style>

// src-tauri/resources/templates/angular-ts/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <main>
      <h1>Hello World!</h1>
      <p>Welcome to your Angular app.</p>
    </main>
  `,
  styles: [`
    main {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      font-family: system-ui, -apple-system, sans-serif;
    }

    h1 {
      font-size: 2rem;
      color: #dd0031;
    }
  `]
})
export class AppComponent {
  title = 'angular-ts-template';
}
